# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  uiSource: 'src'  # Correct variable name for the source code folder
  uiBuild: '$(Build.SourcesDirectory)/build'  # Correct path for build folder

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    cd $(uiSource)  # Use 'cd' instead of 'pushd' for Linux
    npm install
    npm run build
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(uiBuild)'  # Correct reference to the build folder
    includeRootFolder: false  # Usually, we do not need to include the root folder
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Path where the zip file is stored
    ArtifactName: 'drop'
    publishLocation: 'Container'
